# Generated by Django 5.2 on 2025-04-16 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Rajshahi', 'Rajshahi')], max_length=100)),
                ('country', models.CharField(choices=[('Bangladesh', 'Bangladesh')], max_length=100)),
                ('primary_industry', models.CharField(choices=[('Software', 'Software'), ('Finance', 'Finance'), ('Medicine', 'Medicine'), ('Education', 'Education')], max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=255)),
                ('company_size', models.CharField(choices=[('1 - 15', '1 - 15'), ('15 - 40', '15 - 40'), ('40 - 70', '40 - 70'), ('70 - 200', '70 - 200')], max_length=20)),
                ('founded_in', models.PositiveIntegerField()),
                ('linkedin', models.URLField()),
                ('twitter', models.URLField()),
                ('website', models.URLField()),
                ('about_company', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
