# Generated by Django 5.2 on 2025-04-16 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Rajshahi', 'Rajshahi'), ('Dhaka', 'Dhaka')], max_length=100)),
                ('country', models.CharField(choices=[('Bangladesh', 'Bangladesh')], max_length=100)),
                ('experience', models.CharField(choices=[('0-2', '0-2'), ('3-10', '3-10'), ('11-40', '11-40')], max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30)),
                ('language', models.CharField(choices=[('English', 'English'), ('German', 'German'), ('French', 'French')], default='English', max_length=100)),
                ('educational_level', models.CharField(choices=[('None', 'None'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters')], max_length=100)),
                ('twitter', models.URLField()),
                ('linkedin', models.URLField()),
                ('about_candidate', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_type', models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('PhD', 'PhD')], max_length=100)),
                ('course', models.CharField(max_length=255)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('still_schooling_here', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=255)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('still_working_here', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=100)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
    ]
